[versions]
loom = "1.0-SNAPSHOT"
loom_quiltflower = "1.7.+"

github_release = "2.+"
machete = "1.+"

minecraft = "1.19.2"
yarn = "1.19.2+build.28"
forge="1.19.2-43.2.0"
kotlin_forge="3.8.0"

[libraries]
minecraft = { module = "com.mojang:minecraft", version.ref = "minecraft" }
forge = { module = "net.minecraftforge:forge", version.ref = "forge" }
kotlin_forge = { module = "thedarkcolour:kotlinforforge", version.ref = "kotlin_forge" }

[plugins]
loom = { id = "dev.architectury.loom", version.ref = "loom" }
loom_quiltflower = { id = "io.github.juuxel.loom-quiltflower", version.ref = "loom_quiltflower" }

github_release = { id = "com.github.breadmoirai.github-release", version.ref = "github_release" }
machete = { id = "io.github.p03w.machete", version.ref = "machete" }
